// Uzbek Language Translations for MegaDent POS System

module.exports = {
    // Common
    common: {
        welcome: "Xush kelibsiz",
        login: "Kirish",
        logout: "Chiqish",
        save: "Saqlash",
        cancel: "Bekor qilish",
        delete: "O'chirish",
        edit: "Tahrirlash",
        view: "Ko'rish",
        back: "Orqaga",
        backToList: "Ro'yxatga qaytish",
        add: "Qo'shish",
        search: "Qidirish",
        actions: "Amallar",
        status: "Holat",
        date: "Sana",
        total: "Jami",
        notes: "Izohlar",
        required: "Majburiy",
        optional: "Ixtiyoriy",
        yes: "Ha",
        no: "Yo'q",
        confirm: "Tasdiqlash",
    },

    // Authentication
    auth: {
        login: "Tizimga kirish",
        username: "Login",
        password: "Parol",
        loginButton: "Kirish",
        logout: "Chiqish",
        invalidCredentials: "Login yoki parol noto'g'ri",
        loginRequired: "Login va parol kiritilishi shart",
        systemTitle: "MegaDent POS Tizimi",
        systemSubtitle: "Stomatologik uskunalar do'koni boshqaruv tizimi",
        defaultCredentials: "Standart: admin / admin123",
    },

    // Navigation
    nav: {
        dashboard: "Bosh sahifa",
        products: "Mahsulotlar",
        suppliers: "Ta'minotchilar",
        sellers: "Sotuvchilar",
        customers: "Mijozlar",
        stockIntake: "Qabul qilish",
        stockTransfer: "O'tkazish",
        sales: "Sotuvlar",
        debts: "Qarzlar",
    },

    // Dashboard
    dashboard: {
        title: "Bosh sahifa",
        todaySales: "Bugungi sotuvlar",
        thisWeekSales: "Bu hafta",
        thisMonthSales: "Bu oy",
        activeDebts: "Faol qarzlar",
        transactions: "ta tranzaksiya",
        customers: "ta mijoz",
        quickActions: "Tezkor amallar",
        newSale: "Yangi sotuv",
        stockIntake: "Qabul qilish",
        stockTransfer: "O'tkazish",
        addProduct: "Mahsulot qo'shish",
        recentSales: "So'nggi sotuvlar",
        lowStockAlert: "Kam qolgan mahsulotlar",
        noSales: "Hozircha sotuvlar yo'q",
        customer: "Mijoz",
        seller: "Sotuvchi",
        paid: "To'langan",
        remaining: "Qoldiq",
    },

    // Products
    products: {
        title: "Mahsulotlar",
        allProducts: "Barcha mahsulotlar",
        addNew: "Yangi mahsulot qo'shish",
        editProduct: "Mahsulotni tahrirlash",
        productName: "Mahsulot nomi",
        barcode: "Shtrix-kod",
        warranty: "Kafolat (oy)",
        purchasePrice: "Sotib olish narxi",
        sellPrice: "Sotish narxi",
        notFound: "Mahsulotlar topilmadi",
        barcodeExists: "Bu shtrix-kod allaqachon mavjud",
        deleteConfirm: "Ishonchingiz komilmi?",
    },

    // Suppliers
    suppliers: {
        title: "Ta'minotchilar",
        allSuppliers: "Barcha ta'minotchilar",
        addNew: "Yangi ta'minotchi qo'shish",
        editSupplier: "Ta'minotchini tahrirlash",
        supplierName: "Ta'minotchi nomi",
        phone: "Telefon",
        email: "Email",
        address: "Manzil",
        notFound: "Ta'minotchilar topilmadi",
    },

    // Sellers
    sellers: {
        title: "Sotuvchilar",
        allSellers: "Barcha sotuvchilar",
        addNew: "Yangi sotuvchi qo'shish",
        editSeller: "Sotuvchini tahrirlash",
        fullName: "To'liq ismi",
        phone: "Telefon",
        commission: "Komissiya %",
        inventory: "Ombor",
        notFound: "Sotuvchilar topilmadi",
        currentInventory: "Hozirgi ombor",
        noInventory: "Bu sotuvchida ombor mahsulotlari yo'q",
    },

    // Customers
    customers: {
        title: "Mijozlar",
        allCustomers: "Barcha mijozlar",
        addNew: "Yangi mijoz qo'shish",
        editCustomer: "Mijozni tahrirlash",
        fullName: "To'liq ismi",
        phone: "Telefon",
        address: "Manzil",
        notFound: "Mijozlar topilmadi",
        phoneExists: "Bu telefon raqam allaqachon ro'yxatdan o'tgan",
    },

    // Stock Intake
    stockIntake: {
        title: "Qabul qilish",
        allIntakes: "Barcha qabullar",
        newIntake: "Yangi qabul",
        supplier: "Ta'minotchi",
        totalAmount: "Umumiy summa",
        selectSupplier: "Ta'minotchini tanlang",
        products: "Mahsulotlar",
        selectProduct: "Mahsulotni tanlang",
        quantity: "Miqdor",
        purchasePrice: "Sotib olish narxi",
        addProduct: "+ Mahsulot qo'shish",
        saveIntake: "Qabulni saqlash",
        intakeDetails: "Qabul tafsilotlari",
        notFound: "Qabullar topilmadi",
        available: "Mavjud",
    },

    // Stock Transfer
    stockTransfer: {
        title: "O'tkazish",
        allTransfers: "Barcha o'tkazmalar",
        newTransfer: "Yangi o'tkazma",
        transferToSeller: "Sotuvchiga o'tkazish",
        seller: "Sotuvchi",
        selectSeller: "Sotuvchini tanlang",
        productsFromWarehouse: "Ombordan mahsulotlar",
        sellerPrice: "Sotuvchi narxi",
        transferStock: "O'tkazish",
        transferDetails: "O'tkazma tafsilotlari",
        notFound: "O'tkazmalar topilmadi",
        onlyAvailable: "faqat {qty} ta mavjud",
    },

    // Sales
    sales: {
        title: "Sotuvlar",
        allSales: "Barcha sotuvlar",
        newSale: "Yangi sotuv",
        customerInfo: "Mijoz ma'lumotlari",
        customerPhone: "Mijoz telefoni",
        customerName: "Mijoz ismi",
        customerAddress: "Mijoz manzili",
        saleDetails: "Sotuv tafsilotlari",
        seller: "Sotuvchi",
        selectSeller: "Sotuvchini tanlang",
        products: "Mahsulotlar",
        qty: "Dona",
        price: "Narx",
        payment: "To'lov",
        initialPayment: "Boshlang'ich to'lov",
        paymentMethod: "To'lov usuli",
        cash: "Naqd",
        card: "Karta",
        transfer: "O'tkazma",
        other: "Boshqa",
        debtConfig: "Qarz sozlamalari",
        markupType: "Ustama turi",
        fixedAmount: "Qat'iy summa (oylik)",
        percentInterest: "Foiz (oylik foiz)",
        markupValue: "Ustama qiymati",
        gracePeriod: "Imtiyozli muddat (oy)",
        completeSale: "Sotuvni yakunlash",
        saleInfo: "Sotuv ma'lumotlari",
        totalAmount: "Umumiy summa",
        paidAmount: "To'langan",
        remainingAmount: "Qoldiq",
        paid: "To'langan",
        partial: "Qisman",
        unpaid: "To'lanmagan",
        notFound: "Sotuvlar topilmadi",
        paymentHistory: "To'lov tarixi",
        addPayment: "To'lov qo'shish",
        amount: "Summa",
        method: "Usul",
        searchExisting: "Mavjud mijozni qidirish uchun yozing",
        selectSellerFirst: "Avval sotuvchini tanlang",
    },

    // Debts
    debts: {
        title: "Qarzlar",
        totalActiveDebts: "Jami faol qarzlar",
        totalActiveAmount: "Jami faol summa",
        totalRecovered: "Jami qaytarilgan",
        debtManagement: "Qarzlarni boshqarish",
        active: "Faol",
        paid: "To'langan",
        cancelled: "Bekor qilingan",
        customer: "Mijoz",
        saleDate: "Sotuv sanasi",
        originalAmount: "Asl summa",
        currentAmount: "Joriy summa",
        markupType: "Ustama turi",
        graceEnd: "Imtiyoz tugashi",
        fixed: "Qat'iy",
        percent: "Foiz",
        notFound: "qarzlar topilmadi",
        debtDetails: "Qarz tafsilotlari",
        debtInfo: "Qarz ma'lumotlari",
        markupHistory: "Ustama tarixi",
        debtBefore: "Qarz (oldin)",
        markupApplied: "Qo'shilgan ustama",
        debtAfter: "Qarz (keyin)",
        applyMarkupManually: "Ustamani qo'lda qo'shish",
        cancelDebt: "Qarzni bekor qilish",
        confirmApplyMarkup: "Hozir ustama qo'shilsinmi?",
        confirmCancel: "Qarzni bekor qilasizmi?",
        lastMarkupDate: "Oxirgi ustama sanasi",
        never: "Hech qachon",
        monthly: "oylik",
    },

    // Table Headers
    table: {
        id: "ID",
        name: "Nomi",
        barcode: "Shtrix-kod",
        warranty: "Kafolat (oy)",
        purchasePrice: "Sotib olish narxi",
        sellPrice: "Sotish narxi",
        actions: "Amallar",
        phone: "Telefon",
        email: "Email",
        address: "Manzil",
        commission: "Komissiya",
        date: "Sana",
        supplier: "Ta'minotchi",
        seller: "Sotuvchi",
        customer: "Mijoz",
        total: "Jami",
        paid: "To'langan",
        remaining: "Qoldiq",
        status: "Holat",
        quantity: "Miqdor",
        unitPrice: "Birlik narxi",
        subtotal: "Oraliq jami",
        product: "Mahsulot",
        sellerPrice: "Sotuvchi narxi",
        totalValue: "Umumiy qiymat",
        method: "Usul",
        amount: "Summa",
    },

    // Status
    status: {
        paid: "To'langan",
        partial: "Qisman",
        unpaid: "To'lanmagan",
        active: "Faol",
        cancelled: "Bekor qilingan",
    },

    // Validation Messages
    validation: {
        required: "Bu maydon to'ldirilishi shart",
        email: "To'g'ri email manzilini kiriting",
        phone: "To'g'ri telefon raqamini kiriting",
        number: "To'g'ri raqam kiriting",
        positiveNumber: "Musbat raqam kiriting",
        min: "Minimal qiymat: {min}",
        max: "Maksimal qiymat: {max}",
        minLength: "Minimal uzunlik: {length} belgi",
        maxLength: "Maksimal uzunlik: {length} belgi",
        fixErrors: "Iltimos, xatolarni tuzating",
        atLeastOneProduct: "Kamida bitta mahsulot qo'shing",
        insufficientStock: "Omborda yetarli mahsulot yo'q",
        priceBelowMinimum: "Narx minimal narxdan past bo'lishi mumkin emas",
        onlyAvailable: "Faqat {qty} ta mavjud",
    },

    // Error Messages
    error: {
        title: "Xato",
        pageNotFound: "Sahifa topilmadi",
        internalError: "Ichki server xatosi",
        loadFailed: "Yuklash muvaffaqiyatsiz tugadi",
        saveFailed: "Saqlash muvaffaqiyatsiz tugadi",
        deleteFailed: "O'chirish muvaffaqiyatsiz tugadi",
        notFound: "Topilmadi",
        goToDashboard: "Bosh sahifaga o'tish",
    },

    // Success Messages
    success: {
        saved: "Muvaffaqiyatli saqlandi",
        updated: "Muvaffaqiyatli yangilandi",
        deleted: "Muvaffaqiyatli o'chirildi",
        created: "Muvaffaqiyatli yaratildi",
    },

    // Buttons
    buttons: {
        save: "Saqlash",
        cancel: "Bekor qilish",
        delete: "O'chirish",
        edit: "Tahrirlash",
        view: "Ko'rish",
        add: "Qo'shish",
        back: "Orqaga",
        submit: "Yuborish",
        search: "Qidirish",
        login: "Kirish",
        logout: "Chiqish",
        update: "Yangilash",
        create: "Yaratish",
        close: "Yopish",
        confirm: "Tasdiqlash",
        viewAll: "Hammasini ko'rish",
        addNew: "Yangi qo'shish",
    },
};
